#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef CPAYSDK_SWIFT_H
#define CPAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CPaySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC7CPaySDK15CPayBillingAddr")
@interface CPayBillingAddr : NSObject
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckData;
SWIFT_CLASS("_TtC7CPaySDK9CPayCheck")
@interface CPayCheck : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable app;
@property (nonatomic, strong) CPayCheckData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPayment;
SWIFT_CLASS("_TtCC7CPaySDK9CPayCheck13CPayCheckData")
@interface CPayCheckData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic) NSInteger amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCanceled;
@property (nonatomic, copy) NSString * _Nullable expiry;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, strong) CPayCheckDataPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPaymentData;
SWIFT_CLASS("_TtCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment")
@interface CPayCheckDataPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) CPayCheckDataPaymentData * _Nullable data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment24CPayCheckDataPaymentData")
@interface CPayCheckDataPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
SWIFT_CLASS("_TtC7CPaySDK12CPayConsumer")
@interface CPayConsumer : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, strong) NSNumber * _Nullable registrationTime;
@property (nonatomic, copy) NSString * _Nullable registrationIp;
@property (nonatomic, copy) NSString * _Nullable riskLevel;
@property (nonatomic, strong) NSNumber * _Nullable firstInteractionTime;
@property (nonatomic, strong) NSNumber * _Nullable totalTransactionCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CPayENVMode, open) {
  CPayENVModeDEV = 0,
  CPayENVModeQA = 1,
  CPayENVModeUAT = 2,
  CPayENVModePROD = 3,
};

@class CPayExtTransaction;
@class CPayExtDevice;
@class CPayExtApp;
@class CPayExtGateway;
SWIFT_CLASS("_TtC7CPaySDK7CPayExt")
@interface CPayExt : NSObject
@property (nonatomic, strong) CPayExtTransaction * _Nullable transaction;
@property (nonatomic, strong) CPayExtDevice * _Nullable device;
@property (nonatomic, strong) CPayExtApp * _Nullable app;
@property (nonatomic, strong) CPayExtGateway * _Nullable gateway;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK10CPayExtApp")
@interface CPayExtApp : NSObject
@property (nonatomic, copy) NSString * _Nullable appName;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable source;
@property (nonatomic, copy) NSString * _Nullable bundle_id;
@property (nonatomic, copy) NSString * _Nullable sdk_version;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK13CPayExtDevice")
@interface CPayExtDevice : NSObject
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable os;
@property (nonatomic, copy) NSString * _Nullable fingerprint;
@property (nonatomic, copy) NSString * _Nullable osVersion;
@property (nonatomic, copy) NSString * _Nullable model;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayGrant;
@class CPayExtGatewayConsumer;
@class CPayExtGatewayFlight;
@class CPayExtGatewayCar;
@class CPayExtGatewayHotel;
@class CPayExtGatewayTrip;
SWIFT_CLASS("_TtC7CPaySDK14CPayExtGateway")
@interface CPayExtGateway : NSObject
@property (nonatomic, copy) NSString * _Nullable orderId;
@property (nonatomic, copy) NSString * _Nullable orderPayerId;
@property (nonatomic, copy) NSString * _Nullable orderPaymentId;
@property (nonatomic, copy) NSString * _Nullable orderPaymentSource;
@property (nonatomic, copy) NSString * _Nullable authorizationToken;
@property (nonatomic, strong) CPayExtGatewayGrant * _Nullable grant;
@property (nonatomic, strong) CPayExtGatewayConsumer * _Nullable consumer;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlight *> * _Nullable flight;
@property (nonatomic, copy) NSArray<CPayExtGatewayCar *> * _Nullable car;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotel *> * _Nullable hotel;
@property (nonatomic, copy) NSArray<CPayExtGatewayTrip *> * _Nullable trip;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayCarItinerary;
@class CPayExtGatewayCarInsurance;
@class CPayExtGatewayCarDriver;
SWIFT_CLASS("_TtC7CPaySDK17CPayExtGatewayCar")
@interface CPayExtGatewayCar : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarItinerary *> * _Nullable carRentalItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarDriver *> * _Nullable drivers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK23CPayExtGatewayCarDriver")
@interface CPayExtGatewayCarDriver : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayCarInsurance")
@interface CPayExtGatewayCarInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayCarLocation;
SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayCarItinerary")
@interface CPayExtGatewayCarItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable rentalCompany;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable driverId;
@property (nonatomic, strong) CPayExtGatewayCarLocation * _Nullable pickUpLocation;
@property (nonatomic, strong) CPayExtGatewayCarLocation * _Nullable dropOffLocation;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, strong) NSNumber * _Nullable carPrice;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK25CPayExtGatewayCarLocation")
@interface CPayExtGatewayCarLocation : NSObject
@property (nonatomic, copy) NSString * _Nullable streetAddress;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK22CPayExtGatewayConsumer")
@interface CPayExtGatewayConsumer : NSObject
@property (nonatomic, copy) NSString * _Nullable consumerId;
@property (nonatomic, copy) NSString * _Nullable cashtag;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayFlightItinerary;
@class CPayExtGatewayFlightInsurance;
@class CPayExtGatewayFlightPassenger;
SWIFT_CLASS("_TtC7CPaySDK20CPayExtGatewayFlight")
@interface CPayExtGatewayFlight : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightItinerary *> * _Nullable itinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightPassenger *> * _Nullable passengers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightInsurance")
@interface CPayExtGatewayFlightInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightItinerary")
@interface CPayExtGatewayFlightItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable departure;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic, copy) NSString * _Nullable arrival;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic, copy) NSString * _Nullable carrier;
@property (nonatomic, strong) NSNumber * _Nullable segmentPrice;
@property (nonatomic, copy) NSString * _Nullable departureDate;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryMethod;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryRecipient;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable passengerId;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightPassenger")
@interface CPayExtGatewayFlightPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK19CPayExtGatewayGrant")
@interface CPayExtGatewayGrant : NSObject
@property (nonatomic, copy) NSString * _Nullable grantId;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayHotelItinerary;
@class CPayExtGatewayHotelInsurance;
@class CPayExtGatewayHotelPassenger;
SWIFT_CLASS("_TtC7CPaySDK19CPayExtGatewayHotel")
@interface CPayExtGatewayHotel : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelItinerary *> * _Nullable hotelItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelPassenger *> * _Nullable passengers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayHotelAddress")
@interface CPayExtGatewayHotelAddress : NSObject
@property (nonatomic, copy) NSString * _Nullable streetAddress;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelInsurance")
@interface CPayExtGatewayHotelInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelItinerary")
@interface CPayExtGatewayHotelItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable hotelName;
@property (nonatomic, strong) CPayExtGatewayHotelAddress * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, strong) NSNumber * _Nullable numberOfRooms;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable passengerId;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryMethod;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryRecipient;
@property (nonatomic, strong) NSNumber * _Nullable hotelPrice;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelPassenger")
@interface CPayExtGatewayHotelPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayTripItinerary;
@class CPayExtGatewayTripPassenger;
@class CPayExtGatewayTripServices;
SWIFT_CLASS("_TtC7CPaySDK18CPayExtGatewayTrip")
@interface CPayExtGatewayTrip : NSObject
@property (nonatomic, strong) CPayExtGatewayTripItinerary * _Nullable tripItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayTripPassenger *> * _Nullable tripPassengers;
@property (nonatomic, strong) NSNumber * _Nullable minAge;
@property (nonatomic, strong) NSNumber * _Nullable maxAge;
@property (nonatomic, copy) NSArray<CPayExtGatewayTripServices *> * _Nullable services;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK27CPayExtGatewayTripItinerary")
@interface CPayExtGatewayTripItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable initialCountry;
@property (nonatomic, copy) NSString * _Nullable initialCity;
@property (nonatomic, copy) NSString * _Nullable finalCountry;
@property (nonatomic, copy) NSString * _Nullable finalCity;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK27CPayExtGatewayTripPassenger")
@interface CPayExtGatewayTripPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable birthDate;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable uniqueId;
@property (nonatomic, copy) NSString * _Nullable mainPassenger;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayTripServices")
@interface CPayExtGatewayTripServices : NSObject
@property (nonatomic, copy) NSString * _Nullable travelInsurance;
@property (nonatomic, copy) NSString * _Nullable hotel;
@property (nonatomic, copy) NSString * _Nullable flight;
@property (nonatomic, copy) NSString * _Nullable cancelationService;
@property (nonatomic, copy) NSString * _Nullable sharedRoom;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtTransactionReceipt;
SWIFT_CLASS("_TtC7CPaySDK18CPayExtTransaction")
@interface CPayExtTransaction : NSObject
@property (nonatomic, strong) CPayExtTransactionReceipt * _Nullable receipt;
@property (nonatomic, copy) NSString * _Nullable metadata;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK25CPayExtTransactionReceipt")
@interface CPayExtTransactionReceipt : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayProduct;
@class CPayShipping;
SWIFT_CLASS("_TtC7CPaySDK9CPayGoods")
@interface CPayGoods : NSObject
@property (nonatomic, copy) NSArray<CPayProduct *> * _Nullable goods;
@property (nonatomic, strong) CPayShipping * _Nullable shipping;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK16CPayInstallments")
@interface CPayInstallments : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) double paymentNumber;
@property (nonatomic) int32_t quantity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayRequest;
@class CPayResult;
@class UIOpenURLContext;
@class UIApplication;
@class NSURL;
@class NSUserActivity;
SWIFT_CLASS("_TtC7CPaySDK11CPayManager")
@interface CPayManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (CPayManager * _Nonnull)sharedInst SWIFT_WARN_UNUSED_RESULT;
/// Used to set the runtime environment. See @CPayENVMode
/// \param mode An enumeration variable of CPayENVMode.
///
///
/// returns:
/// true if successful.
- (BOOL)setMode:(enum CPayENVMode)mode;
/// Set up an access token for accessing the API.
/// \param token Generated by Citcon.
///
///
/// returns:
/// true if successful.
- (BOOL)setAccessToken:(NSString * _Nonnull)token;
/// Request an order to complete payment.
/// \param order An instance of the CPayRequest class. See @CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the payment has been made. It depends on the callback.
- (BOOL)requestOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback;
/// Query information about an order.
/// \param transId Specifies the id of the order.
///
/// \param callback A callback function of type @CPayCheckCallback. It will be called when query is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (BOOL)inquireOrder:(NSString * _Nonnull)transId callback:(void (^ _Nonnull)(CPayCheck * _Nullable))callback;
/// Get the version of the SDK.
///
/// returns:
/// SDK version.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// It is called in the delegate method scene:openURLContexts of SceneDelegate.
/// note:
/// UPOP crashes because UIAlert is used in iOS target iOS 13.
/// \param URLContexts Instance of class NSSet passed by SceneDelegate.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (void)handleScene:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
/// It is called in the delegate method application:openURL:options of AppDelegate.
/// \param app Instance of class UIApplication passed by AppDelegate.
///
/// \param url Instance of class URL passed by AppDelegate.
///
/// \param options Instance of class NSDictionary passed by AppDelegate.
///
///
/// returns:
/// false.
- (BOOL)handleUrl:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// If WeChat payment is used, it is called in the delegate method application:continueUserActivity:restorationHandler of AppDelegate.
/// Or it is called in the delegate method scene:continueUserActivity of SceneDelegate.
/// \param userActivity Instance of class NSUserActivity passed by AppDelegate.
///
///
/// returns:
/// Void
- (void)handleUniversalLink:(NSUserActivity * _Nonnull)userActivity;
/// Get an access token signed by Citcon.
/// <ul>
///   <li>
///     Note This function only used by test. Will remove in official realse.
///   </li>
/// </ul>
/// \param callback The callback function will be called after get access token
///
///
/// returns:
/// Void
- (void)getAccessToken:(NSString * _Nonnull)vendor onComplete:(void (^ _Nonnull)(NSString * _Nullable))callback;
/// Generate an order for prepare charge
/// \param order An instance of CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// Void
- (void)generateOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback;
@end

@class CPayPaymentData;
SWIFT_CLASS("_TtC7CPaySDK11CPayPayment")
@interface CPayPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable indicator;
@property (nonatomic) BOOL requestToken;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable client;
@property (nonatomic, strong) NSNumber * _Nullable expiry;
@property (nonatomic, copy) NSString * _Nullable format;
@property (nonatomic, strong) CPayPaymentData * _Nullable data;
@property (nonatomic, strong) CPayBillingAddr * _Nullable billingAddress;
@property (nonatomic, copy) NSString * _Nullable nonce;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayPaymentData")
@interface CPayPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable issuer;
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK11CPayProduct")
@interface CPayProduct : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, strong) NSNumber * _Nullable quantity;
@property (nonatomic, strong) NSNumber * _Nullable totalAmount;
@property (nonatomic, strong) NSNumber * _Nullable unitAmount;
@property (nonatomic, strong) NSNumber * _Nullable totalTaxRate;
@property (nonatomic, strong) NSNumber * _Nullable totalTaxAmount;
@property (nonatomic, strong) NSNumber * _Nullable totalDiscountAmount;
@property (nonatomic, strong) NSNumber * _Nullable taxableAmount;
@property (nonatomic, strong) NSNumber * _Nullable taxExemptAmount;
@property (nonatomic, copy) NSString * _Nullable totalDiscountCode;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, strong) NSNumber * _Nullable unitTaxAmount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayTranscation;
@class CPayUrls;
@class UIViewController;
SWIFT_CLASS("_TtC7CPaySDK11CPayRequest")
@interface CPayRequest : NSObject
@property (nonatomic, strong) CPayTranscation * _Nonnull transaction;
@property (nonatomic, strong) CPayConsumer * _Nullable consumer;
@property (nonatomic, strong) CPayPayment * _Nullable payment;
@property (nonatomic, strong) CPayGoods * _Nullable goods;
@property (nonatomic, strong) CPayInstallments * _Nullable installments;
@property (nonatomic, strong) CPayUrls * _Nonnull urls;
@property (nonatomic, strong) CPayExt * _Nullable ext;
@property (nonatomic, copy) NSString * _Nullable scheme;
@property (nonatomic, copy) NSString * _Nullable universalLink;
@property (nonatomic) BOOL request3DSecureVerification;
@property (nonatomic, strong) UIViewController * _Nullable controller;
@property (nonatomic, copy) NSString * _Nullable unionpayMode;
@property (nonatomic, copy) NSString * _Nullable paypalClientId;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultData;
SWIFT_CLASS("_TtC7CPaySDK10CPayResult")
@interface CPayResult : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, strong) CPayResultData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultPayment;
SWIFT_CLASS("_TtCC7CPaySDK10CPayResult14CPayResultData")
@interface CPayResultData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amount;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic) NSInteger timeAuthorized;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
@property (nonatomic, strong) CPayResultPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCCC7CPaySDK10CPayResult14CPayResultData17CPayResultPayment")
@interface CPayResultPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayRuntimeInst")
@interface CPayRuntimeInst : NSObject
+ (NSString * _Nonnull)NTFY_ASYNC SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)ORDER_CONFIRMED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK12CPayShipping")
@interface CPayShipping : NSObject
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSNumber * _Nullable amount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UIColor;
@class UIFont;
SWIFT_CLASS("_TtC7CPaySDK16CPayStyleManager")
@interface CPayStyleManager : NSObject
/// Create CashApp Button
/// \param size string, value are small、large, default is large
///
/// \param action 
///
///
/// returns:
/// UIView
+ (UIView * _Nullable)buildCashAppPaymentButtonWithSize:(NSString * _Nullable)size action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
/// Create CashApp Method View
/// \param size string, value are small、large, default is large
///
/// \param cashTag string, default is “”
///
/// \param cashTagColor UIColor
///
/// \param cashTagFont UIFont
///
///
/// returns:
/// UIView
+ (UIView * _Nullable)buildCashAppPaymentMethodWithSize:(NSString * _Nullable)size cashTag:(NSString * _Nonnull)cashTag cashTagColor:(UIColor * _Nullable)cashTagColor cashTagFont:(UIFont * _Nullable)cashTagFont SWIFT_WARN_UNUSED_RESULT;
/// Check if KlarnaExt framework is available at runtime
///
/// returns:
/// true if KlarnaExt is available
+ (BOOL)hasKlarnaOSM SWIFT_WARN_UNUSED_RESULT;
/// Create Klarna On-Site Messaging (OSM) view using runtime reflection
/// \param clientId Klarna client ID
///
/// \param placementKey OSM placement key (e.g., “credit-promotion-badge”, “top-strip-promotion-auto-size”)
///
/// \param locale Locale string (default: “en-US”)
///
/// \param purchaseAmount Optional purchase amount in cents (e.g., 10000 for $100.00)
///
/// \param region Klarna region (default: “NA” for North America, also supports “EU”, “OC”)
///
/// \param environment Klarna environment (default: “playground”, also supports “production”)
///
/// \param theme UI theme (default: “light”, also supports “dark”)
///
/// \param onHeightChanged Optional closure called when OSM view height changes
///
/// \param completion Callback with OSM view or error
///
///
/// returns:
/// true if OSM view creation was initiated, false if KlarnaExt is not available
+ (BOOL)buildKlarnaOSMViewWithClientId:(NSString * _Nonnull)clientId placementKey:(NSString * _Nonnull)placementKey locale:(NSString * _Nonnull)locale purchaseAmount:(NSNumber * _Nullable)purchaseAmount region:(NSString * _Nullable)region environment:(NSString * _Nullable)environment theme:(NSString * _Nullable)theme onHeightChanged:(void (^ _Nullable)(CGFloat))onHeightChanged completion:(void (^ _Nonnull)(UIView * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayTranscation")
@interface CPayTranscation : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic, strong) NSNumber * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable vertical;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK8CPayUrls")
@interface CPayUrls : NSObject
@property (nonatomic, copy) NSString * _Nullable ipn;
@property (nonatomic, copy) NSString * _Nullable success;
@property (nonatomic, copy) NSString * _Nullable cancel;
@property (nonatomic, copy) NSString * _Nullable fail;
@property (nonatomic, copy) NSString * _Nullable mobile;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef CPAYSDK_SWIFT_H
#define CPAYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CPaySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC7CPaySDK15CPayBillingAddr")
@interface CPayBillingAddr : NSObject
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckData;
SWIFT_CLASS("_TtC7CPaySDK9CPayCheck")
@interface CPayCheck : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable app;
@property (nonatomic, strong) CPayCheckData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPayment;
SWIFT_CLASS("_TtCC7CPaySDK9CPayCheck13CPayCheckData")
@interface CPayCheckData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic) NSInteger amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCanceled;
@property (nonatomic, copy) NSString * _Nullable expiry;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, strong) CPayCheckDataPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayCheckDataPaymentData;
SWIFT_CLASS("_TtCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment")
@interface CPayCheckDataPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) CPayCheckDataPaymentData * _Nullable data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCCCC7CPaySDK9CPayCheck13CPayCheckData20CPayCheckDataPayment24CPayCheckDataPaymentData")
@interface CPayCheckDataPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
SWIFT_CLASS("_TtC7CPaySDK12CPayConsumer")
@interface CPayConsumer : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, strong) NSNumber * _Nullable registrationTime;
@property (nonatomic, copy) NSString * _Nullable registrationIp;
@property (nonatomic, copy) NSString * _Nullable riskLevel;
@property (nonatomic, strong) NSNumber * _Nullable firstInteractionTime;
@property (nonatomic, strong) NSNumber * _Nullable totalTransactionCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CPayENVMode, open) {
  CPayENVModeDEV = 0,
  CPayENVModeQA = 1,
  CPayENVModeUAT = 2,
  CPayENVModePROD = 3,
};

@class CPayExtTransaction;
@class CPayExtDevice;
@class CPayExtApp;
@class CPayExtGateway;
SWIFT_CLASS("_TtC7CPaySDK7CPayExt")
@interface CPayExt : NSObject
@property (nonatomic, strong) CPayExtTransaction * _Nullable transaction;
@property (nonatomic, strong) CPayExtDevice * _Nullable device;
@property (nonatomic, strong) CPayExtApp * _Nullable app;
@property (nonatomic, strong) CPayExtGateway * _Nullable gateway;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK10CPayExtApp")
@interface CPayExtApp : NSObject
@property (nonatomic, copy) NSString * _Nullable appName;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, copy) NSString * _Nullable source;
@property (nonatomic, copy) NSString * _Nullable bundle_id;
@property (nonatomic, copy) NSString * _Nullable sdk_version;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK13CPayExtDevice")
@interface CPayExtDevice : NSObject
@property (nonatomic, copy) NSString * _Nullable ip;
@property (nonatomic, copy) NSString * _Nullable os;
@property (nonatomic, copy) NSString * _Nullable fingerprint;
@property (nonatomic, copy) NSString * _Nullable osVersion;
@property (nonatomic, copy) NSString * _Nullable model;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayGrant;
@class CPayExtGatewayConsumer;
@class CPayExtGatewayFlight;
@class CPayExtGatewayCar;
@class CPayExtGatewayHotel;
@class CPayExtGatewayTrip;
SWIFT_CLASS("_TtC7CPaySDK14CPayExtGateway")
@interface CPayExtGateway : NSObject
@property (nonatomic, copy) NSString * _Nullable orderId;
@property (nonatomic, copy) NSString * _Nullable orderPayerId;
@property (nonatomic, copy) NSString * _Nullable orderPaymentId;
@property (nonatomic, copy) NSString * _Nullable orderPaymentSource;
@property (nonatomic, copy) NSString * _Nullable authorizationToken;
@property (nonatomic, strong) CPayExtGatewayGrant * _Nullable grant;
@property (nonatomic, strong) CPayExtGatewayConsumer * _Nullable consumer;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlight *> * _Nullable flight;
@property (nonatomic, copy) NSArray<CPayExtGatewayCar *> * _Nullable car;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotel *> * _Nullable hotel;
@property (nonatomic, copy) NSArray<CPayExtGatewayTrip *> * _Nullable trip;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayCarItinerary;
@class CPayExtGatewayCarInsurance;
@class CPayExtGatewayCarDriver;
SWIFT_CLASS("_TtC7CPaySDK17CPayExtGatewayCar")
@interface CPayExtGatewayCar : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarItinerary *> * _Nullable carRentalItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayCarDriver *> * _Nullable drivers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK23CPayExtGatewayCarDriver")
@interface CPayExtGatewayCarDriver : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayCarInsurance")
@interface CPayExtGatewayCarInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayCarLocation;
SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayCarItinerary")
@interface CPayExtGatewayCarItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable rentalCompany;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable driverId;
@property (nonatomic, strong) CPayExtGatewayCarLocation * _Nullable pickUpLocation;
@property (nonatomic, strong) CPayExtGatewayCarLocation * _Nullable dropOffLocation;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, strong) NSNumber * _Nullable carPrice;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK25CPayExtGatewayCarLocation")
@interface CPayExtGatewayCarLocation : NSObject
@property (nonatomic, copy) NSString * _Nullable streetAddress;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK22CPayExtGatewayConsumer")
@interface CPayExtGatewayConsumer : NSObject
@property (nonatomic, copy) NSString * _Nullable consumerId;
@property (nonatomic, copy) NSString * _Nullable cashtag;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayFlightItinerary;
@class CPayExtGatewayFlightInsurance;
@class CPayExtGatewayFlightPassenger;
SWIFT_CLASS("_TtC7CPaySDK20CPayExtGatewayFlight")
@interface CPayExtGatewayFlight : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightItinerary *> * _Nullable itinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayFlightPassenger *> * _Nullable passengers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightInsurance")
@interface CPayExtGatewayFlightInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightItinerary")
@interface CPayExtGatewayFlightItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable departure;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic, copy) NSString * _Nullable arrival;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic, copy) NSString * _Nullable carrier;
@property (nonatomic, strong) NSNumber * _Nullable segmentPrice;
@property (nonatomic, copy) NSString * _Nullable departureDate;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryMethod;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryRecipient;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable passengerId;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK29CPayExtGatewayFlightPassenger")
@interface CPayExtGatewayFlightPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK19CPayExtGatewayGrant")
@interface CPayExtGatewayGrant : NSObject
@property (nonatomic, copy) NSString * _Nullable grantId;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayHotelItinerary;
@class CPayExtGatewayHotelInsurance;
@class CPayExtGatewayHotelPassenger;
SWIFT_CLASS("_TtC7CPaySDK19CPayExtGatewayHotel")
@interface CPayExtGatewayHotel : NSObject
@property (nonatomic, copy) NSString * _Nullable pnr;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelItinerary *> * _Nullable hotelItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelInsurance *> * _Nullable insurance;
@property (nonatomic, copy) NSArray<CPayExtGatewayHotelPassenger *> * _Nullable passengers;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayHotelAddress")
@interface CPayExtGatewayHotelAddress : NSObject
@property (nonatomic, copy) NSString * _Nullable streetAddress;
@property (nonatomic, copy) NSString * _Nullable postalCode;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelInsurance")
@interface CPayExtGatewayHotelInsurance : NSObject
@property (nonatomic, copy) NSString * _Nullable insuranceCompany;
@property (nonatomic, copy) NSString * _Nullable insuranceType;
@property (nonatomic, strong) NSNumber * _Nullable insurancePrice;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelItinerary")
@interface CPayExtGatewayHotelItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable hotelName;
@property (nonatomic, strong) CPayExtGatewayHotelAddress * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
@property (nonatomic, strong) NSNumber * _Nullable numberOfRooms;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable passengerId;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryMethod;
@property (nonatomic, copy) NSString * _Nullable ticketDeliveryRecipient;
@property (nonatomic, strong) NSNumber * _Nullable hotelPrice;
@property (nonatomic, copy) NSString * _Nullable clasName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK28CPayExtGatewayHotelPassenger")
@interface CPayExtGatewayHotelPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtGatewayTripItinerary;
@class CPayExtGatewayTripPassenger;
@class CPayExtGatewayTripServices;
SWIFT_CLASS("_TtC7CPaySDK18CPayExtGatewayTrip")
@interface CPayExtGatewayTrip : NSObject
@property (nonatomic, strong) CPayExtGatewayTripItinerary * _Nullable tripItinerary;
@property (nonatomic, copy) NSArray<CPayExtGatewayTripPassenger *> * _Nullable tripPassengers;
@property (nonatomic, strong) NSNumber * _Nullable minAge;
@property (nonatomic, strong) NSNumber * _Nullable maxAge;
@property (nonatomic, copy) NSArray<CPayExtGatewayTripServices *> * _Nullable services;
@property (nonatomic, copy) NSString * _Nullable affiliateName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK27CPayExtGatewayTripItinerary")
@interface CPayExtGatewayTripItinerary : NSObject
@property (nonatomic, copy) NSString * _Nullable initialCountry;
@property (nonatomic, copy) NSString * _Nullable initialCity;
@property (nonatomic, copy) NSString * _Nullable finalCountry;
@property (nonatomic, copy) NSString * _Nullable finalCity;
@property (nonatomic, copy) NSString * _Nullable startTime;
@property (nonatomic, copy) NSString * _Nullable endTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK27CPayExtGatewayTripPassenger")
@interface CPayExtGatewayTripPassenger : NSObject
@property (nonatomic, strong) NSNumber * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable birthDate;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable uniqueId;
@property (nonatomic, copy) NSString * _Nullable mainPassenger;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK26CPayExtGatewayTripServices")
@interface CPayExtGatewayTripServices : NSObject
@property (nonatomic, copy) NSString * _Nullable travelInsurance;
@property (nonatomic, copy) NSString * _Nullable hotel;
@property (nonatomic, copy) NSString * _Nullable flight;
@property (nonatomic, copy) NSString * _Nullable cancelationService;
@property (nonatomic, copy) NSString * _Nullable sharedRoom;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayExtTransactionReceipt;
SWIFT_CLASS("_TtC7CPaySDK18CPayExtTransaction")
@interface CPayExtTransaction : NSObject
@property (nonatomic, strong) CPayExtTransactionReceipt * _Nullable receipt;
@property (nonatomic, copy) NSString * _Nullable metadata;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK25CPayExtTransactionReceipt")
@interface CPayExtTransactionReceipt : NSObject
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayProduct;
@class CPayShipping;
SWIFT_CLASS("_TtC7CPaySDK9CPayGoods")
@interface CPayGoods : NSObject
@property (nonatomic, copy) NSArray<CPayProduct *> * _Nullable goods;
@property (nonatomic, strong) CPayShipping * _Nullable shipping;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK16CPayInstallments")
@interface CPayInstallments : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) double paymentNumber;
@property (nonatomic) int32_t quantity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayRequest;
@class CPayResult;
@class UIOpenURLContext;
@class UIApplication;
@class NSURL;
@class NSUserActivity;
SWIFT_CLASS("_TtC7CPaySDK11CPayManager")
@interface CPayManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (CPayManager * _Nonnull)sharedInst SWIFT_WARN_UNUSED_RESULT;
/// Used to set the runtime environment. See @CPayENVMode
/// \param mode An enumeration variable of CPayENVMode.
///
///
/// returns:
/// true if successful.
- (BOOL)setMode:(enum CPayENVMode)mode;
/// Set up an access token for accessing the API.
/// \param token Generated by Citcon.
///
///
/// returns:
/// true if successful.
- (BOOL)setAccessToken:(NSString * _Nonnull)token;
/// Request an order to complete payment.
/// \param order An instance of the CPayRequest class. See @CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the payment has been made. It depends on the callback.
- (BOOL)requestOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback;
/// Query information about an order.
/// \param transId Specifies the id of the order.
///
/// \param callback A callback function of type @CPayCheckCallback. It will be called when query is complete.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (BOOL)inquireOrder:(NSString * _Nonnull)transId callback:(void (^ _Nonnull)(CPayCheck * _Nullable))callback;
/// Get the version of the SDK.
///
/// returns:
/// SDK version.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// It is called in the delegate method scene:openURLContexts of SceneDelegate.
/// note:
/// UPOP crashes because UIAlert is used in iOS target iOS 13.
/// \param URLContexts Instance of class NSSet passed by SceneDelegate.
///
///
/// returns:
/// true if the call was successful, but does not mean the query has completed. It depends on the callback.
- (void)handleScene:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
/// It is called in the delegate method application:openURL:options of AppDelegate.
/// \param app Instance of class UIApplication passed by AppDelegate.
///
/// \param url Instance of class URL passed by AppDelegate.
///
/// \param options Instance of class NSDictionary passed by AppDelegate.
///
///
/// returns:
/// false.
- (BOOL)handleUrl:(UIApplication * _Nonnull)app open:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
/// If WeChat payment is used, it is called in the delegate method application:continueUserActivity:restorationHandler of AppDelegate.
/// Or it is called in the delegate method scene:continueUserActivity of SceneDelegate.
/// \param userActivity Instance of class NSUserActivity passed by AppDelegate.
///
///
/// returns:
/// Void
- (void)handleUniversalLink:(NSUserActivity * _Nonnull)userActivity;
/// Get an access token signed by Citcon.
/// <ul>
///   <li>
///     Note This function only used by test. Will remove in official realse.
///   </li>
/// </ul>
/// \param callback The callback function will be called after get access token
///
///
/// returns:
/// Void
- (void)getAccessToken:(NSString * _Nonnull)vendor onComplete:(void (^ _Nonnull)(NSString * _Nullable))callback;
/// Generate an order for prepare charge
/// \param order An instance of CPayRequest.
///
/// \param callback A callback function of type @CPayRequestCallback. It will be called when payment is complete.
///
///
/// returns:
/// Void
- (void)generateOrder:(CPayRequest * _Nonnull)order callback:(void (^ _Nonnull)(CPayResult * _Nullable))callback;
@end

@class CPayPaymentData;
SWIFT_CLASS("_TtC7CPaySDK11CPayPayment")
@interface CPayPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSString * _Nullable indicator;
@property (nonatomic) BOOL requestToken;
@property (nonatomic, copy) NSString * _Nullable token;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable client;
@property (nonatomic, strong) NSNumber * _Nullable expiry;
@property (nonatomic, copy) NSString * _Nullable format;
@property (nonatomic, strong) CPayPaymentData * _Nullable data;
@property (nonatomic, strong) CPayBillingAddr * _Nullable billingAddress;
@property (nonatomic, copy) NSString * _Nullable nonce;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayPaymentData")
@interface CPayPaymentData : NSObject
@property (nonatomic, copy) NSString * _Nullable issuer;
@property (nonatomic, copy) NSString * _Nullable pan;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable expiry;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK11CPayProduct")
@interface CPayProduct : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, copy) NSString * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, strong) NSNumber * _Nullable quantity;
@property (nonatomic, strong) NSNumber * _Nullable totalAmount;
@property (nonatomic, strong) NSNumber * _Nullable unitAmount;
@property (nonatomic, strong) NSNumber * _Nullable totalTaxRate;
@property (nonatomic, strong) NSNumber * _Nullable totalTaxAmount;
@property (nonatomic, strong) NSNumber * _Nullable totalDiscountAmount;
@property (nonatomic, strong) NSNumber * _Nullable taxableAmount;
@property (nonatomic, strong) NSNumber * _Nullable taxExemptAmount;
@property (nonatomic, copy) NSString * _Nullable totalDiscountCode;
@property (nonatomic, copy) NSString * _Nullable productType;
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, strong) NSNumber * _Nullable unitTaxAmount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayTranscation;
@class CPayUrls;
@class UIViewController;
SWIFT_CLASS("_TtC7CPaySDK11CPayRequest")
@interface CPayRequest : NSObject
@property (nonatomic, strong) CPayTranscation * _Nonnull transaction;
@property (nonatomic, strong) CPayConsumer * _Nullable consumer;
@property (nonatomic, strong) CPayPayment * _Nullable payment;
@property (nonatomic, strong) CPayGoods * _Nullable goods;
@property (nonatomic, strong) CPayInstallments * _Nullable installments;
@property (nonatomic, strong) CPayUrls * _Nonnull urls;
@property (nonatomic, strong) CPayExt * _Nullable ext;
@property (nonatomic, copy) NSString * _Nullable scheme;
@property (nonatomic, copy) NSString * _Nullable universalLink;
@property (nonatomic) BOOL request3DSecureVerification;
@property (nonatomic, strong) UIViewController * _Nullable controller;
@property (nonatomic, copy) NSString * _Nullable unionpayMode;
@property (nonatomic, copy) NSString * _Nullable paypalClientId;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultData;
SWIFT_CLASS("_TtC7CPaySDK10CPayResult")
@interface CPayResult : NSObject
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable version;
@property (nonatomic, strong) CPayResultData * _Nonnull data;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CPayResultPayment;
SWIFT_CLASS("_TtCC7CPaySDK10CPayResult14CPayResultData")
@interface CPayResultData : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable object;
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic) NSInteger amount;
@property (nonatomic) NSInteger amountCaptured;
@property (nonatomic) NSInteger amountRefunded;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic) NSInteger timeCreated;
@property (nonatomic) NSInteger timeAuthorized;
@property (nonatomic) NSInteger timeCaptured;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
@property (nonatomic, strong) CPayResultPayment * _Nullable payment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtCCC7CPaySDK10CPayResult14CPayResultData17CPayResultPayment")
@interface CPayResultPayment : NSObject
@property (nonatomic, copy) NSString * _Nullable method;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayRuntimeInst")
@interface CPayRuntimeInst : NSObject
+ (NSString * _Nonnull)NTFY_ASYNC SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)ORDER_CONFIRMED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK12CPayShipping")
@interface CPayShipping : NSObject
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable street;
@property (nonatomic, copy) NSString * _Nullable street2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSNumber * _Nullable amount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
@class UIColor;
@class UIFont;
SWIFT_CLASS("_TtC7CPaySDK16CPayStyleManager")
@interface CPayStyleManager : NSObject
/// Create CashApp Button
/// \param size string, value are small、large, default is large
///
/// \param action 
///
///
/// returns:
/// UIView
+ (UIView * _Nullable)buildCashAppPaymentButtonWithSize:(NSString * _Nullable)size action:(void (^ _Nonnull)(void))action SWIFT_WARN_UNUSED_RESULT;
/// Create CashApp Method View
/// \param size string, value are small、large, default is large
///
/// \param cashTag string, default is “”
///
/// \param cashTagColor UIColor
///
/// \param cashTagFont UIFont
///
///
/// returns:
/// UIView
+ (UIView * _Nullable)buildCashAppPaymentMethodWithSize:(NSString * _Nullable)size cashTag:(NSString * _Nonnull)cashTag cashTagColor:(UIColor * _Nullable)cashTagColor cashTagFont:(UIFont * _Nullable)cashTagFont SWIFT_WARN_UNUSED_RESULT;
/// Check if KlarnaExt framework is available at runtime
///
/// returns:
/// true if KlarnaExt is available
+ (BOOL)hasKlarnaOSM SWIFT_WARN_UNUSED_RESULT;
/// Create Klarna On-Site Messaging (OSM) view using runtime reflection
/// \param clientId Klarna client ID
///
/// \param placementKey OSM placement key (e.g., “credit-promotion-badge”, “top-strip-promotion-auto-size”)
///
/// \param locale Locale string (default: “en-US”)
///
/// \param purchaseAmount Optional purchase amount in cents (e.g., 10000 for $100.00)
///
/// \param region Klarna region (default: “NA” for North America, also supports “EU”, “OC”)
///
/// \param environment Klarna environment (default: “playground”, also supports “production”)
///
/// \param theme UI theme (default: “light”, also supports “dark”)
///
/// \param onHeightChanged Optional closure called when OSM view height changes
///
/// \param completion Callback with OSM view or error
///
///
/// returns:
/// true if OSM view creation was initiated, false if KlarnaExt is not available
+ (BOOL)buildKlarnaOSMViewWithClientId:(NSString * _Nonnull)clientId placementKey:(NSString * _Nonnull)placementKey locale:(NSString * _Nonnull)locale purchaseAmount:(NSNumber * _Nullable)purchaseAmount region:(NSString * _Nullable)region environment:(NSString * _Nullable)environment theme:(NSString * _Nullable)theme onHeightChanged:(void (^ _Nullable)(CGFloat))onHeightChanged completion:(void (^ _Nonnull)(UIView * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK15CPayTranscation")
@interface CPayTranscation : NSObject
@property (nonatomic, copy) NSString * _Nullable reference;
@property (nonatomic, strong) NSNumber * _Nullable amount;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic) BOOL autoCapture;
@property (nonatomic, copy) NSString * _Nullable note;
@property (nonatomic, copy) NSString * _Nullable vertical;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC7CPaySDK8CPayUrls")
@interface CPayUrls : NSObject
@property (nonatomic, copy) NSString * _Nullable ipn;
@property (nonatomic, copy) NSString * _Nullable success;
@property (nonatomic, copy) NSString * _Nullable cancel;
@property (nonatomic, copy) NSString * _Nullable fail;
@property (nonatomic, copy) NSString * _Nullable mobile;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
