#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef KLARNAEXT_SWIFT_H
#define KLARNAEXT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KlarnaExt",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class UIView;
@class KlarnaPaymentManager;
@class NSNumber;
@class NSURL;
@class KlarnaOSMManager;
/// Main entry point for KlarnaExt framework
/// Provides simplified interface for Klarna payment integration
SWIFT_CLASS("_TtC9KlarnaExt12KlarnaExtSDK")
@interface KlarnaExtSDK : NSObject
/// Shared instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KlarnaExtSDK * _Nonnull shared;)
+ (KlarnaExtSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Framework version
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull frameworkVersion;)
+ (NSString * _Nonnull)frameworkVersion SWIFT_WARN_UNUSED_RESULT;
/// Check if KlarnaExt framework is properly imported
+ (BOOL)hasImported SWIFT_WARN_UNUSED_RESULT;
/// Create and initialize a payment manager
/// \param clientToken Client token from backend
///
/// \param category Payment category (e.g., “pay_now”, “pay_later”)
///
/// \param returnURL App URL scheme for return
///
/// \param completion Callback with payment view or error
///
///
/// returns:
/// KlarnaPaymentManager instance
- (KlarnaPaymentManager * _Nonnull)createPaymentManagerWithClientToken:(NSString * _Nonnull)clientToken category:(NSString * _Nonnull)category returnURL:(NSString * _Nonnull)returnURL completion:(void (^ _Nonnull)(UIView * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
/// Create and initialize an OSM manager
/// \param clientId Klarna client ID
///
/// \param placementKey OSM placement key
///
/// \param locale Locale string (default: “en-US”)
///
/// \param purchaseAmount Optional purchase amount in cents
///
/// \param region Klarna region (e.g., “NA”, “EU”, “OC”)
///
/// \param environment Klarna environment (“playground” or “production”)
///
/// \param theme UI theme (“light” or “dark”)
///
/// \param returnURL Return URL for redirects
///
/// \param onEvent Closure called when Klarna events occur (eventName, eventData)
///
/// \param onHeightChanged Closure called when OSM view height changes
///
/// \param completion Callback with OSM view or error
///
///
/// returns:
/// KlarnaOSMManager instance
- (KlarnaOSMManager * _Nonnull)createOSMManagerWithClientId:(NSString * _Nonnull)clientId placementKey:(NSString * _Nonnull)placementKey locale:(NSString * _Nonnull)locale purchaseAmount:(NSNumber * _Nullable)purchaseAmount region:(NSString * _Nullable)region environment:(NSString * _Nullable)environment theme:(NSString * _Nullable)theme returnURL:(NSURL * _Nullable)returnURL onEvent:(void (^ _Nullable)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nullable))onEvent onHeightChanged:(void (^ _Nullable)(CGFloat))onHeightChanged completion:(void (^ _Nonnull)(UIView * _Nullable, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end

/// Manager class for handling Klarna On-Site Messaging (OSM) views
SWIFT_CLASS("_TtC9KlarnaExt16KlarnaOSMManager")
@interface KlarnaOSMManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSError;
/// Protocol matching KlarnaPaymentEventListener from KlarnaMobileSDK
SWIFT_PROTOCOL("_TtP9KlarnaExt34KlarnaPaymentEventListenerProtocol_")
@protocol KlarnaPaymentEventListenerProtocol
- (void)klarnaInitializedWithPaymentView:(UIView * _Nonnull)paymentView;
- (void)klarnaLoadedWithPaymentView:(UIView * _Nonnull)paymentView;
- (void)klarnaLoadedPaymentReviewWithPaymentView:(UIView * _Nonnull)paymentView;
- (void)klarnaAuthorizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken finalizeRequired:(BOOL)finalizeRequired;
- (void)klarnaReauthorizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
- (void)klarnaFinalizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
- (void)klarnaResizedWithPaymentView:(UIView * _Nonnull)paymentView to:(CGFloat)newHeight;
- (void)klarnaFailedInPaymentView:(UIView * _Nonnull)paymentView withError:(NSError * _Nonnull)error;
@end

/// Manager class for handling Klarna payment view initialization and authorization
SWIFT_CLASS("_TtC9KlarnaExt20KlarnaPaymentManager")
@interface KlarnaPaymentManager : NSObject
/// Initialize payment view with client token
/// \param clientToken The client token received from backend
///
/// \param category Payment method category (e.g., “pay_now”, “pay_later”, “pay_over_time”)
///
/// \param returnURL URL scheme for returning to app
///
/// \param completion Callback with payment view or error
///
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken category:(NSString * _Nonnull)category returnURL:(NSString * _Nonnull)returnURL completion:(void (^ _Nonnull)(UIView * _Nullable, NSError * _Nullable))completion;
/// Authorize the payment session
/// \param autoFinalize Whether to auto-finalize after authorization
///
/// \param completion Callback with authorization token, approval status, and error
///
- (void)authorizeWithAutoFinalize:(BOOL)autoFinalize completion:(void (^ _Nonnull)(NSString * _Nullable, BOOL, NSError * _Nullable))completion;
/// Finalize the payment (if autoFinalize was false)
- (void)finalizePayment;
/// Load payment view content
- (void)load;
/// Cleanup resources
- (void)cleanup;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface KlarnaPaymentManager (SWIFT_EXTENSION(KlarnaExt)) <KlarnaPaymentEventListenerProtocol>
/// Called when payment view is initialized successfully
- (void)klarnaInitializedWithPaymentView:(UIView * _Nonnull)paymentView;
/// Called when payment view content is loaded
- (void)klarnaLoadedWithPaymentView:(UIView * _Nonnull)paymentView;
/// Called when payment review is loaded (optional step)
- (void)klarnaLoadedPaymentReviewWithPaymentView:(UIView * _Nonnull)paymentView;
/// Called when authorization is completed
- (void)klarnaAuthorizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken finalizeRequired:(BOOL)finalizeRequired;
/// Called when reauthorization is completed
- (void)klarnaReauthorizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// Called when finalization is completed
- (void)klarnaFinalizedWithPaymentView:(UIView * _Nonnull)paymentView approved:(BOOL)approved authToken:(NSString * _Nullable)authToken;
/// Called when payment view height changes
- (void)klarnaResizedWithPaymentView:(UIView * _Nonnull)paymentView to:(CGFloat)newHeight;
/// Called when an error occurs
- (void)klarnaFailedInPaymentView:(UIView * _Nonnull)paymentView withError:(NSError * _Nonnull)error;
@end

/// Protocol matching KlarnaPaymentView from KlarnaMobileSDK
SWIFT_PROTOCOL("_TtP9KlarnaExt25KlarnaPaymentViewProtocol_")
@protocol KlarnaPaymentViewProtocol
- (void)initializeWithClientToken:(NSString * _Nonnull)clientToken returnUrl:(NSURL * _Nonnull)returnUrl;
- (void)authorizeWithAutoFinalize:(BOOL)autoFinalize jsonData:(NSString * _Nullable)jsonData;
- (void)finaliseWithJsonData:(NSString * _Nullable)jsonData;
- (void)loadWithJsonData:(NSString * _Nullable)jsonData;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
